name: Swift

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
    - name: Build
      env: 
        DEVELOPER_DIR: /Applications/Xcode_13.2.1.app
      run: swiftc -parse-as-library -O unxip.swift
    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        path: unxip
